export const COL_NAMES = [
  {headerItem: '№', overlay: null}, {headerItem: 'Ticker', overlay: null}, {headerItem: 'Price', overlay: 'Цена закрытия предыдущего рабочего дня'}, 
  {headerItem: 'Market cap', overlay: 'Капитализация, млрд. $'}, {headerItem: 'PE', overlay: 'Цена/Прибыль'}, 
  {headerItem: 'Fwd PE 2023', overlay: 'Цена/Прибыль, где Цена - цена закрытия предыдущего рабочего дня, Прибыль - EPS в 2023 году по мнению аналитиков'}, 
  {headerItem: 'Fwd PE 2024', overlay: 'Цена/Прибыль, где Цена - цена закрытия предыдущего рабочего дня, Прибыль - EPS в 2024 году по мнению аналитиков'},
  {headerItem: 'Fwd PE 2025', overlay: 'Цена/Прибыль, где Цена - цена закрытия предыдущего рабочего дня, Прибыль - EPS в 2025 году по мнению аналитиков'},
  {headerItem: 'Fwd EPS growth', overlay: 'Будущий среднегодой рост EPS по мнению аналитиков'}, 
  {headerItem: 'Earnings growth past 3y', overlay: 'Среднегодой рост прибыли за последние 3 года'}, 
  {headerItem: 'PS', overlay: 'Капитализация/Выручка'},
  {headerItem: 'Fwd PS 2023', overlay: 'Капитализация/Выручка, где Капитализация - капитализация компании на предыдущий рабочей день, Выручка - выручка в 2023 году по мнению аналитиков'}, 
  {headerItem: 'Fwd PS 2024', overlay: 'Капитализация/Выручка, где Капитализация - капитализация компании на предыдущий рабочей день, Выручка - выручка в 2024 году по мнению аналитиков'},
  {headerItem: 'Fwd PS 2025', overlay: 'Капитализация/Выручка, где Капитализация - капитализация компании на предыдущий рабочей день, Выручка - выручка в 2025 году по мнению аналитиков'},
  {headerItem: 'Fwd sales growth', overlay: 'Будущий среднегодой рост выручки по мнению аналитиков'}, 
  {headerItem: 'Sales growth past 3y', overlay: 'Среднегодой рост выручки за последние 3 года'},
  {headerItem: 'REG Ratio', overlay: 'Коэффициент, сопоставляющий цену акции с прибылью на акцию и ожидаемой будущей прибылью компании'},
  {headerItem: 'EV/ Ebitda', overlay: 'Отношение стоимости компании к полученной ею прибыли до вычета процентов, налога на прибыль и амортизации активов'},
  {headerItem: 'Net margin', overlay: 'Чистая прибыль, %'},
  {headerItem: 'ROE', overlay: 'Рентабельность собственного капитала - коэффициент, отражающий эффективность управления компанией капиталом, вложенным акционерами'},
  {headerItem: 'ROA', overlay: 'Рентабельность активов - коэффициент, отражающий эффективность использования активов компании для генерации выручки'},
  {headerItem: 'Cash/ Debt', overlay: 'Коэффициент покрытия текущего долга наличными средствами, показывает сколько раз компания может погасить свои текущие обязательства, используя денежные средства от операционной деятельности'},
  {headerItem: 'Interest Coverage', overlay: 'Коэффициент покрытия процентов характеризует способность организации обслуживать свои долговые обязательства: EBIT/ Проценты к уплате'},
  {headerItem: 'Current Ratio', overlay: 'Коэффициент коказывает способность компании погашать краткосрочные обязательства: Оборотные активы/ Краткосрочные обязательства'},
  {headerItem: 'Debt/ Equity', overlay: 'Чистый долг/Собственный капитал'},
  {headerItem: 'Dividend yield', overlay: 'Дивидендная доходность за прошедший год, %'},
  {headerItem: 'Payout Ratio', overlay: 'Коэффициент выплаты дивидендов - показывает соотношение общей суммы дивидендов, выплаченных акционерам по отношению к чистой прибыли'},
  {headerItem: 'Price/ LFCF', overlay: 'Капитализация/ Левериджный cвободный денежный поток'},
  {headerItem: 'RSI 14 days', overlay: 'Relative Strength Index, Индекс относительной силы, период - 14 дней'},
  {headerItem: 'Growth Rating', overlay: 'Авторская оценка (по 10 бальной шкале) "Роста" потоков компании на основании: среднегодого роста выручки и EPS в будущем (по мнению аналитиков) и за последние 3 года'},
  {headerItem: 'Profit Rating', overlay: 'Авторская оценка (по 10 бальной шкале) "Рентабельности" компании на основании: чистой прибыли, ROE и ROA'},
  {headerItem: 'Value Rating', overlay: 'Авторская оценка (по 10 бальной шкале) "Стоимости" компании на основании: PE, PS, REG ratio, EV/ Ebitda'},
  {headerItem: 'Debt Rating', overlay: 'Авторская оценка (по 10 бальной шкале) "Долговой нагрузки" компании на основании: Cash/ Debt, Interest Coverage, Current Ratio и Debt/ Equity'},
  {headerItem: 'Dividend Rating', overlay: 'Авторская оценка (по 10 бальной шкале) "Выплаты дивидендов" компанией на основании: Дивидендной доходности за прошедший год и Payout Ratio'},
  {headerItem: 'FCF Rating', overlay: 'Авторская оценка (по 10 бальной шкале) "Свободного денежного потока" компании на основании: Price/ LFCF'},
  {headerItem: 'Momentum Rating', overlay: 'Авторская оценка (по 10 бальной шкале) "Momentum" цены акции на основании: RSI 14 days'},
  {headerItem: 'Total Rating', overlay: 'Авторская "Совокупная" оценка (по 10 бальной шкале) компании на основании: Growth Rating, Profit Rating, Value Rating, Debt Rating, Dividend Rating, FCF Rating, Momentum Rating'},
]

export const COL_NAMES_DB = ["Tickers", "Price", "Market_cap", "PE", "Fwd_PE_1", "Fwd_PE_2", "Fwd_PE_3", 
                            "Fwd_avg_EPS_growth", "Last_eps_growth3", "PS", "Fwd_PS_1", "Fwd_PS_2", "Fwd_PS_3", 
                            "Fwd_avg_sales_growth", "Last_rev_growth3", "Peg_ratio", "EvEbitda", "Net_margin", "ROE", "ROA", 
                            "Cash_Debt", "Interest_coverage", "Current_ratio", "DebtToEquity", "Div_yield", "Payout_ratio", 
                            "priceCF", "RSI14", "Growth_Rating", "Profit_Rating", "Value_Rating", "Debt_Rating", 
                            "Divident_Rating", "FCF_Rating", "Momentum_Rating", "Total_Rating",
]

export const optionsSort = [
    { value: 'Market_cap', label: 'Капитализации' },
    { value: 'PE', label: 'PE' },
    { value: 'Fwd_PE_1', label: 'Fwd PE 2023' },
    { value: 'Fwd_PE_2', label: 'Fwd PE 2024' },
    { value: 'Fwd_PE_3', label: 'Fwd PE 2025' },
    { value: 'Fwd_avg_EPS_growth', label: 'Fwd среднему росту EPS' },
    { value: 'Last_eps_growth3', label: 'Среднему росту Earnings за последние 3 года' },
    { value: 'PS', label: 'PS' },
    { value: 'Fwd_PS_1', label: 'Fwd PS 2023' },
    { value: 'Fwd_PS_2', label: 'Fwd PS 2024' },
    { value: 'Fwd_PS_3', label: 'Fwd PS 2025' },
    { value: 'Fwd_avg_sales_growth', label: 'Fwd среднему росту выручки' },
    { value: 'Last_rev_growth3', label: 'Среднему росту выручки за последние 3 года' },
    { value: 'Peg_ratio', label: 'PEG ratio' },
    { value: 'EvEbitda', label: 'EV/Ebitda' },
    { value: 'Net_margin', label: 'Чистой прибыли' },
    { value: 'ROE', label: 'ROE' },
    { value: 'ROA', label: 'ROA' },
    { value: 'Cash_Debt', label: 'Cash/Debt' },
    { value: 'Interest_coverage', label: 'Interest coverage' },
    { value: 'Current_ratio', label: 'Current ratio' },
    { value: 'DebtToEquity', label: 'Debt/Equity' },
    { value: 'Div_yield', label: 'Дивидендной доходности' },
    { value: 'Payout_ratio', label: 'Payout ratio' },
    { value: 'priceCF', label: 'Капитализация/Свободный денежный поток' },
    { value: 'RSI14', label: 'RSI 14 days' },
    { value: 'Growth_Rating', label: 'Growth Rating' },
    { value: 'Profit_Rating', label: 'Profit Rating' },
    { value: 'Value_Rating', label: 'Value Rating' },
    { value: 'Debt_Rating', label: 'Debt Rating' },
    { value: 'Divident_Rating', label: 'Divident Rating' },
    { value: 'FCF_Rating', label: 'Free Cash Flow Rating' },
    { value: 'Momentum_Rating', label: 'Momentum Rating' },
    { value: 'Total_Rating', label: 'Total Rating' },
  ]